In [3]:
import pandas as pd
data = pd.read_csv("books.csv")
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1354 entries, 0 to 1353
Data columns (total 23 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   book_id                    1354 non-null   int64
 1   goodreads_book_id          1354 non-null   int64
 2   best_book_id               1354 non-null   int64
 3   work_id                    1354 non-null   int64
 4   books_count                1354 non-null   int64
 5   isbn                       1302 non-null   object
 6   isbn13                     1310 non-null   float64
 7   authors                    1354 non-null   object
 8   original_publication_year  1351 non-null   float64
 9   original_title             1302 non-null   object
 10  title                      1354 non-null   object
 11  language_code              1245 non-null   object
 12  average_rating             1354 non-null   float64
 13  ratings_count              1354 non-null   int64
 14  work_ratings_count         1354 non-null   int64
 15  work_text_reviews_count    1354 non-null   int64
 16  ratings_1                  1354 non-null   int64
 17  ratings_2                  1354 non-null   int64
 18  ratings_3                  1354 non-null   int64
 19  ratings_4                  1354 non-null   int64
 20  ratings_5                  1354 non-null   int64
 21  image_url                  1354 non-null   object
 22  small_image_url            1354 non-null   object
dtypes: float64(3), int64(13), object(7)
memory usage: 243.4+ KB

In [4]:
##print the first 5 rows
data.head()

,book_id,goodreads_book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPré",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,6,11870085,11870085,16827462,226,525478817,9.780525e+12,John Green,2012.0,The Fault in Our Stars,...,2346404,2478609,140739,47994,92723,327550,698471,1311871,https://images.gr-assets.com/books/1360206420m...,https://images.gr-assets.com/books/1360206420s...
4,12,13335037,13335037,13155899,210,62024035,9.780062e+12,Veronica Roth,2011.0,Divergent,...,1903563,2216814,101023,36315,82870,310297,673028,1114304,https://images.gr-assets.com/books/1328559506m...,https://images.gr-assets.com/books/1328559506s...

In [6]:
#change the desired data into numeric
data['ratings_count'] = pd.to_numeric(data['ratings_count'], errors='coerce')
data['average_rating'] = data['average_rating'].astype(float)

#clean these 3 columns from the null values they contain
data.dropna(subset=['title', 'ratings_count', 'average_rating'], inplace=True)

harry_potter_books = data[data['title'].str.contains("Harry Potter")]
most_selling_harry_potter = harry_potter_books.nlargest(10, 'ratings_count')

In [12]:
# Find the most selling books within the Harry Potter series:
print("Most Selling Harry Potter Books:")
print(most_selling_harry_potter[['title', 'ratings_count']])

Most Selling Harry Potter Books:
                                                  title  ratings_count
1     Harry Potter and the Sorcerer's Stone (Harry P...        4602479
6     Harry Potter and the Prisoner of Azkaban (Harr...        1832823
9     Harry Potter and the Chamber of Secrets (Harry...        1779331
10    Harry Potter and the Goblet of Fire (Harry Pot...        1753043
11    Harry Potter and the Deathly Hallows (Harry Po...        1746574
8     Harry Potter and the Order of the Phoenix (Har...        1735368
12    Harry Potter and the Half-Blood Prince (Harry ...        1678823
96             Harry Potter Boxset (Harry Potter, #1-7)         190050
613        Harry Potter Collection (Harry Potter, #1-6)          24618
1036  The Magical Worlds of Harry Potter: A Treasury...          13820

In [11]:
#Calculate the average rating of the Harry Potter books.
average_rating_harry_potter = harry_potter_books['average_rating'].mean()
print("\nAverage Rating of Harry Potter Books:")
average_rating_harry_potter

Average Rating of Harry Potter Books:

4.482727272727273